### ISSUE TITLE
Question regarding setting multiple cookies

### ISSUE THREAD

**Issue by Northernside** [elysiajs/elysia-cookie#1]
As [this](https://github.com/elysiajs/elysia-cookie#caveat) states, that in Bun 0.1.4 it is not possible to set multiple cookies at once, does it work though in Bun 0.5(.2)?

**Comment by Northernside** [comment]
bump?

**Comment by SaltyAom** [comment]
Hi, sorry for the slow response.

You can set multiple cookies at once by:
- update `elysia` to minimum version of `^0.2.6`
- update `@elysiajs/cookie` to minimum version of `^0.1.1`

To set multiple response, simply use `setCookie` multiple times in the handler:
```typescript
import { Elysia } from 'elysia'
import { cookie } from '@elysiajs/cookie'

const app = new Elysia()
    .use(cookie())
    .get('/multi', ({ cookie, setCookie }) => {
        setCookie('a', 'b')
        setCookie('c', 'd')

        return cookie
    })
```

Feels free to re-open the issue if this doesn't work, the answer isn't clear or have more related questions to setting multiple cookies.
