### ISSUE TITLE
Type error when using elysia 0.4.x

### ISSUE THREAD

**Issue by Tirke** [elysiajs/elysia-cookie#2]
We can't use this package with elysia 0.4 because of an incompatible returned type :)

**Comment by SaltyAom** [comment]
Right, this is a bug in `bun install`, and has reported in [Elysia #29](https://github.com/elysiajs/elysia/issues/29)

> Deleting node_modules and bun.lockb, and re-installing solve the problem, for some reason.

Additional context:
> This might sound weird but while I was able to replicate the error, seems like Bun accidentally installed an experimental channel instead of stable randomly causing the type error.
>
> To verify, can you please go into node_modules/@elysiajs/static, the correct results should be no node_modules folder inside, but if so, can you please go inside the node_modules/@elysiajs/static/node_modules/elysia/package.json and see if the version match your installed version.
>
> If this happens, can you try deleting node_modules, and bun.lockb and reinstall again using bun install, restart your IDE if needed, and see if the problem stills persists?
>
> If the issue still persists, can you please try again with either npm / yarn / pnpm to see if the problem still occurs?
> 
> Additionally, I found that, this occurs only when you update from elysia version with plugin installed.
>
> So, suppose you previously has Elysia 0.3.1 installed with @elysiajs/cookie, @elysiajs/static, and @elysiajs/swagger, and then update to Elysia 0.3.2, bun install for some reason, will grab the latest release (regardless of channel) instead of reusing the installed module.
> 
> Deleting node_modules and bun.lockb solve the problem, for some reason.

Let me know if this helps solve your problem.

**Comment by Tirke** [comment]
It worked, thanks :)
